services:
  mysql:
    image: mysql
    container_name: furniture-database
    restart: always
    networks:
      - furniture-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: furniture
      MYSQL_USER: furniture
      MYSQL_PASSWORD: furniture
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/db.sql:/docker-entrypoint-initdb.d/init.sql

  furniture-be:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: furniture-be
    restart: always
    networks:
      - furniture-network
    ports:
      - "80:3000"

volumes:
  mysql_data:


networks:
  furniture-network:
