import { env } from './env.config';

const jwtConfig = {
  JWT_CUSTOMER_SECRET: env.JWT_CUSTOMER_SECRET,
  JWT_CUSTOMER_REFRESH_SECRET: env.JWT_CUSTOMER_REFRESH_SECRET,
  JWT_CUSTOMER_EXPIRES_IN: env.JWT_CUSTOMER_EXPIRES_IN,
  JWT_CUSTOMER_REFRESH_EXPIRES_IN: env.JWT_CUSTOMER_REFRESH_EXPIRES_IN,
  JWT_SELLER_SECRET: env.JWT_SELLER_SECRET,
  JWT_SELLER_REFRESH_SECRET: env.JWT_SELLER_REFRESH_SECRET,
  JWT_SELLER_EXPIRES_IN: env.JWT_SELLER_EXPIRES_IN,
  JWT_SELLER_REFRESH_EXPIRES_IN: env.JWT_SELLER_REFRESH_EXPIRES_IN,
};

export default jwtConfig;
